[
    "Paracetamol",
    "Ibuprofeno",
    "Aspirina",
    "Omeprazol",
    "Amoxicilina",
    "Loratadina",
    "Atorvastatina",
    "Metformina",
    "Sertralina",
    "Losartán",
    "Metoprolol",
    "Simvastatina"
]
